import hmac
import hashlib
import os
import logging
import json
import time
import jwt
import httpx
import datetime
import asyncio

from fastapi import FastAPI, Request, HTTPException, Header, BackgroundTasks
from dotenv import load_dotenv
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type
from contextlib import asynccontextmanager
from pydantic import BaseModel
from typing import List, Optional

# -----------------------------
# 🔧 Setup
# -----------------------------
load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

GITHUB_SECRET = os.getenv("GITHUB_WEBHOOK_SECRET")
APP_ID = os.getenv("GITHUB_APP_ID")
PRIVATE_KEY_PATH = os.getenv("PRIVATE_KEY_PATH")

if not GITHUB_SECRET or not APP_ID or not PRIVATE_KEY_PATH:
    raise RuntimeError("Missing required environment variables")

if not os.path.exists(PRIVATE_KEY_PATH):
    raise RuntimeError("PRIVATE_KEY_PATH is invalid")

with open(PRIVATE_KEY_PATH, "r") as f:
    PRIVATE_KEY = f.read()

# -----------------------------
# 🌐 Lifespan (HTTP Client)
# -----------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    timeout = httpx.Timeout(timeout=10.0, connect=10.0, read=45.0, write=10.0, pool=10.0)
    limits = httpx.Limits(max_connections=50, max_keepalive_connections=20)

    app.state.client = httpx.AsyncClient(
        timeout=timeout,
        limits=limits,
        headers={"Accept": "application/vnd.github+json"}
    )

    logger.info("HTTP client initialized")
    yield

    await app.state.client.aclose()
    logger.info("HTTP client closed")

app = FastAPI(title="GitHub PR Bot", lifespan=lifespan)

# -----------------------------
# 🧱 Models
# -----------------------------
class FileStats(BaseModel):
    added: List[str] = []
    modified: List[str] = []
    removed: List[str] = []


class PRComment(BaseModel):
    title: Optional[str] = None
    summary: Optional[str] = None
    pr_number: Optional[int] = None
    repository: Optional[str] = None
    total_files: Optional[int] = None
    file_stats: Optional[FileStats] = None
    notes: Optional[str] = None

    def build_body(self) -> str:
        lines = []

        if self.title:
            lines.append(f"## {self.title}")

        if self.summary:
            lines.append(self.summary)

        if self.pr_number and self.repository:
            lines.append(f"\n📦 **Repo:** `{self.repository}`")
            lines.append(f"🔢 **PR:** #{self.pr_number}")

        if self.total_files is not None:
            lines.append(f"📁 **Files changed:** {self.total_files}")

        if self.file_stats:
            if self.file_stats.added:
                lines.append("\n### ➕ Added Files")
                lines.extend([f"- `{f}`" for f in self.file_stats.added])

            if self.file_stats.modified:
                lines.append("\n### ✏️ Modified Files")
                lines.extend([f"- `{f}`" for f in self.file_stats.modified])

            if self.file_stats.removed:
                lines.append("\n### ❌ Removed Files")
                lines.extend([f"- `{f}`" for f in self.file_stats.removed])

        if self.notes:
            lines.append(f"\n💡 {self.notes}")

        lines.append("\n---\n🤖 Generated by PR Bot")

        return "\n".join(lines)

    def to_github_payload(self):
        return {"body": self.build_body()}

# -----------------------------
# 🔐 Verify Signature
# -----------------------------
def verify_signature(payload_body: bytes, signature: str):
    if not signature:
        raise HTTPException(400, "Missing signature")

    sha_name, sig = signature.split("=")

    mac = hmac.new(
        GITHUB_SECRET.encode(),
        msg=payload_body,
        digestmod=hashlib.sha256,
    )

    if not hmac.compare_digest(mac.hexdigest(), sig):
        raise HTTPException(403, "Invalid signature")

# -----------------------------
# 🔑 JWT
# -----------------------------
def generate_jwt():
    now = int(time.time()) - 30
    payload = {"iat": now, "exp": now + 600, "iss": APP_ID}
    token = jwt.encode(payload, PRIVATE_KEY, algorithm="RS256")
    return token.decode() if isinstance(token, bytes) else token

# -----------------------------
# 🎟️ Token
# -----------------------------
async def get_installation_token(installation_id: int, client: httpx.AsyncClient):
    res = await client.post(
        f"https://api.github.com/app/installations/{installation_id}/access_tokens",
        headers={"Authorization": f"Bearer {generate_jwt()}"}
    )
    if res.status_code != 201:
        raise HTTPException(500, "Token generation failed")
    return res.json()["token"]

# -----------------------------
# 📄 Fetch File
# -----------------------------
@retry(
    stop=stop_after_attempt(4),
    wait=wait_exponential(multiplier=0.5, min=1, max=10),
    retry=retry_if_exception_type((httpx.RequestError,)),
    reraise=True,
)
async def fetch_file_content(owner, repo, path, ref, token, client):
    if not path or not ref:
        return None

    res = await client.get(
        f"https://api.github.com/repos/{owner}/{repo}/contents/{path}?ref={ref}",
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3.raw"}
    )
    return res.text if res.status_code == 200 else None

# -----------------------------
# 📥 PR Data
# -----------------------------
async def fetch_pr_details_and_files(owner, repo, pr, token, client):
    pr_res = await client.get(
        f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr}",
        headers={"Authorization": f"Bearer {token}"}
    )
    pr_data = pr_res.json()

    files, page = [], 1
    while True:
        res = await client.get(
            f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr}/files",
            headers={"Authorization": f"Bearer {token}"},
            params={"page": page, "per_page": 100}
        )
        data = res.json()
        if not data:
            break
        files.extend(data)
        page += 1

    return files, pr_data

# -----------------------------
# 💬 Comment
# -----------------------------
async def comment_pr(owner, repo, pr, comment: PRComment, token, client):
    await client.post(
        f"https://api.github.com/repos/{owner}/{repo}/issues/{pr}/comments",
        headers={"Authorization": f"Bearer {token}"},
        json=comment.to_github_payload()
    )

# -----------------------------
# ✅ Review (Approve / Reject)
# -----------------------------
async def review_pr(owner, repo, pr, token, client, event: str, message: str):
    await client.post(
        f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr}/reviews",
        headers={"Authorization": f"Bearer {token}"},
        json={"event": event, "body": message}
    )

def should_auto_approve(files):
    return len(files) <= 20

# -----------------------------
# 🚀 Process PR
# -----------------------------
async def process_pr(owner, repo, pr, installation_id):
    client = app.state.client

    try:
        token = await get_installation_token(installation_id, client)
        files, pr_data = await fetch_pr_details_and_files(owner, repo, pr, token, client)

        semaphore = asyncio.Semaphore(10)

        async def process_file(f):
            filename = f["filename"]
            status = f.get("status", "modified")

            async def fetch_safe(path, ref):
                async with semaphore:
                    return await fetch_file_content(owner, repo, path, ref, token, client)

            before = fetch_safe(f.get("previous_filename") or filename, pr_data["base"]["sha"]) \
                if status in ["modified", "removed", "renamed"] else asyncio.sleep(0, result=None)

            after = fetch_safe(filename, pr_data["head"]["sha"]) \
                if status in ["modified", "added", "renamed"] else asyncio.sleep(0, result=None)

            before_content, after_content = await asyncio.gather(before, after)

            return {"file": filename, "status": status}

        structured_files = await asyncio.gather(*(process_file(f) for f in files))

        # 🧠 Build comment
        comment = PRComment(
            title="✅ PR Processed Successfully",
            summary="All files analyzed and structured.",
            pr_number=pr,
            repository=f"{owner}/{repo}",
            total_files=len(structured_files),
            file_stats=FileStats(
                added=[f["file"] for f in structured_files if f["status"] == "added"],
                modified=[f["file"] for f in structured_files if f["status"] == "modified"],
                removed=[f["file"] for f in structured_files if f["status"] == "removed"],
            ),
            notes="Auto-approved because changes are small."
        )

        # ⚡ Run comment + review in parallel
        await asyncio.gather(
            comment_pr(owner, repo, pr, comment, token, client),
            review_pr(
                owner, repo, pr, token, client,
                "APPROVE" if should_auto_approve(structured_files) else "REQUEST_CHANGES",
                "✅ Auto-approved" if should_auto_approve(structured_files) else "⚠️ Too large PR"
            )
        )

    except Exception as e:
        logger.error(f"Error: {e}", exc_info=True)

# -----------------------------
# 🎯 Webhook
# -----------------------------
@app.post("/webhook/github")
async def webhook(
    request: Request,
    background_tasks: BackgroundTasks,
    x_hub_signature_256: str = Header(None),
    x_github_event: str = Header(None),
):
    body = await request.body()
    verify_signature(body, x_hub_signature_256)

    payload = json.loads(body)

    if x_github_event != "pull_request":
        return {"msg": "ignored"}

    if payload.get("action") not in ["opened", "synchronize", "reopened"]:
        return {"msg": "ignored"}

    installation = payload.get("installation")
    if not installation:
        return {"msg": "no installation"}

    background_tasks.add_task(
        process_pr,
        payload["repository"]["owner"]["login"],
        payload["repository"]["name"],
        payload["pull_request"]["number"],
        installation["id"]
    )

    return {"status": "processing"}

# -----------------------------
# ❤️ Health
# -----------------------------
@app.get("/health")
async def health():
    return {"status": "ok"}


GITHUB_APP_ID=3349601
GITHUB_WEBHOOK_SECRET=my_ngrok_secret
PRIVATE_KEY_PATH=private-key.pem
