import os
import time
import jwt
import httpx
import logging
from typing import List, Optional, Dict
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

# -----------------------------
# 🔧 Setup & Configuration
# -----------------------------
load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger(__name__)

APP_ID = os.getenv("GITHUB_APP_ID")
PRIVATE_KEY = os.getenv("PRIVATE_KEY")


# -----------------------------
# 🧱 Models
# -----------------------------
class FileStats(BaseModel):
    """Data model tracking the classification of files modified within a Pull Request.

    Attributes:
        added (List[str]): List of file paths added in the PR.
        modified (List[str]): List of file paths modified in the PR.
        removed (List[str]): List of file paths removed in the PR.
    """
    added: List[str] = []
    modified: List[str] = []
    removed: List[str] = []


class PRComment(BaseModel):
    """Data model for constructing structured Markdown summaries for GitHub PR reviews.

    Attributes:
        title (Optional[str]): The main header title for the comment.
        summary (Optional[str]): A brief summary message of the analysis.
        pr_number (Optional[int]): Target Pull Request identity number.
        repository (Optional[str]): Full name of the repository (owner/repo).
        total_files (Optional[int]): Total count of altered files.
        file_stats (Optional[FileStats]): Segmented breakdown of file statuses.
        notes (Optional[str]): Additional automated system notes or dynamic insights.
    """
    title: Optional[str] = None
    summary: Optional[str] = None
    pr_number: Optional[int] = None
    repository: Optional[str] = None
    total_files: Optional[int] = None
    file_stats: Optional[FileStats] = None
    notes: Optional[str] = None

    def build_body(self) -> str:
        """Assembles model attributes into a clean, formatted Markdown string.

        Returns:
            str: Markdown-formatted text ready for a GitHub issue or PR comment.
        """
        lines = []
        if self.title: lines.append(f"## {self.title}")
        if self.summary: lines.append(self.summary)

        if self.pr_number and self.repository:
            lines.append(f"\n📦 **Repo:** `{self.repository}`")
            lines.append(f"🔢 **PR:** #{self.pr_number}")

        if self.total_files is not None:
            lines.append(f"📁 **Files changed:** {self.total_files}")

        if self.file_stats:
            if self.file_stats.added:
                lines.append("\n### ➕ Added Files")
                lines.extend([f"- `{f}`" for f in self.file_stats.added])
            if self.file_stats.modified:
                lines.append("\n### ✏️ Modified Files")
                lines.extend([f"- `{f}`" for f in self.file_stats.modified])
            if self.file_stats.removed:
                lines.append("\n### ❌ Removed Files")
                lines.extend([f"- `{f}`" for f in self.file_stats.removed])

        if self.notes: lines.append(f"\n💡 {self.notes}")
        lines.append("\n---\n🤖 Generated by PR Bot via Request Engine")
        return "\n".join(lines)

    def to_github_payload(self) -> Dict[str, str]:
        """Formats the comment body into a standard GitHub API request payload structure.

        Returns:
            Dict[str, str]: JSON payload dictionary containing the comment text.
        """
        return {"body": self.build_body()}


# -----------------------------
# 🔑 Authentication Engine
# -----------------------------
def generate_jwt() -> str:
    """Generates a JSON Web Token (JWT) signed with the GitHub App private key.

    Uses an RS256 algorithm. Includes a 30-second clock skew buffer for creation time.

    Returns:
        str: Encoded JWT string authorized for GitHub App administrative requests.
    """
    now = int(time.time()) - 30
    payload = {"iat": now, "exp": now + 600, "iss": APP_ID}
    token = jwt.encode(payload, PRIVATE_KEY, algorithm="RS256")
    return token.decode() if isinstance(token, bytes) else token


async def get_installation_token_by_repo(owner: str, repo: str, client: httpx.AsyncClient) -> Optional[str]:
    """Retrieves an ephemeral installation access token for a repository target.

    Queries the GitHub API to find the specific installation ID mapping for the repository, 
    then exchanges the primary JWT for a scoped repository access token.

    Args:
        owner (str): Owner or organization name of the repository.
        repo (str): Name of the repository.
        client (httpx.AsyncClient): HTTPX async client to process network requests.

    Returns:
        Optional[str]: Short-lived installation access token if successful, else None.
    """
    jwt_token = generate_jwt()
    res = await client.get(
        f"https://api.github.com/repos/{owner}/{repo}/installation",
        headers={"Authorization": f"Bearer {jwt_token}"}
    )
    if res.status_code != 200:
        logger.error(f"Could not find App installation metadata for {owner}/{repo}.")
        return None
        
    installation_id = res.json()["id"]
    token_res = await client.post(
        f"https://api.github.com/app/installations/{installation_id}/access_tokens",
        headers={"Authorization": f"Bearer {jwt_token}"}
    )
    if token_res.status_code != 201:
        logger.error(f"Token generation failed for installation {installation_id}")
        return None
    return token_res.json()["token"]


# -----------------------------
# 📄 GitHub API Handlers
# -----------------------------
async def fetch_single_pull_request(owner: str, repo: str, pr_number: int, token: str, client: httpx.AsyncClient) -> Dict:
    """Fetches base metadata for a specified GitHub Pull Request.

    Args:
        owner (str): Owner or organization name of the repository.
        repo (str): Name of the repository.
        pr_number (int): Identity number of the target pull request.
        token (str): Repository installation access token.
        client (httpx.AsyncClient): HTTPX async client to process network requests.

    Returns:
        Dict: Parsed JSON payload containing high-level PR details.

    Raises:
        HTTPException: If GitHub responds with a non-200 status code.
    """
    res = await client.get(
        f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}",
        headers={"Authorization": f"Bearer {token}"}
    )
    if res.status_code != 200:
        raise HTTPException(status_code=res.status_code, detail=f"Failed to fetch PR #{pr_number}: {res.text}")
    return res.json()


@retry(
    stop=stop_after_attempt(4),
    wait=wait_exponential(multiplier=0.5, min=1, max=10),
    retry=retry_if_exception_type((httpx.RequestError,)),
    reraise=True,
)
async def fetch_file_content(owner: str, repo: str, path: str, ref: str, token: str, client: httpx.AsyncClient) -> Optional[str]:
    """Retrieves the raw text contents of a file at a specific commit reference point.

    Includes automatic exponential backoff retry mechanics handling network exceptions.

    Args:
        owner (str): Owner or organization name of the repository.
        repo (str): Name of the repository.
        path (str): Target internal system path to the file.
        ref (str): Commit SHA or branch reference point to target.
        token (str): Repository installation access token.
        client (httpx.AsyncClient): HTTPX async client to process network requests.

    Returns:
        Optional[str]: Raw text payload string from the file if successful, else None.
    """
    if not path or not ref:
        return None
    res = await client.get(
        f"https://api.github.com/repos/{owner}/{repo}/contents/{path}?ref={ref}",
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3.raw"}
    )
    return res.text if res.status_code == 200 else None


async def fetch_pr_files(owner: str, repo: str, pr: int, token: str, client: httpx.AsyncClient) -> List[Dict]:
    """Iterates over paginated results to retrieve all file data entries included in a PR.

    Args:
        owner (str): Owner or organization name of the repository.
        repo (str): Name of the repository.
        pr (int): Target Pull Request ID number.
        token (str): Repository installation access token.
        client (httpx.AsyncClient): HTTPX async client to process network requests.

    Returns:
        List[Dict]: Comprehensive aggregated list of file dictionary elements from GitHub.
    """
    files, page = [], 1
    while True:
        res = await client.get(
            f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr}/files",
            headers={"Authorization": f"Bearer {token}"},
            params={"page": page, "per_page": 100}
        )
        data = res.json()
        if not data:
            break
        files.extend(data)
        page += 1
    return files


async def comment_pr(owner: str, repo: str, pr: int, comment: PRComment, token: str, client: httpx.AsyncClient) -> None:
    """Posts a high-level standalone Markdown summary comment onto a Pull Request thread.

    Args:
        owner (str): Owner or organization name of the repository.
        repo (str): Name of the repository.
        pr (int): Target Pull Request ID number.
        comment (PRComment): Structure model entity defining the text components.
        token (str): Repository installation access token.
        client (httpx.AsyncClient): HTTPX async client to process network requests.
    """
    await client.post(
        f"https://api.github.com/repos/{owner}/{repo}/issues/{pr}/comments",
        headers={"Authorization": f"Bearer {token}"},
        json=comment.to_github_payload()
    )


async def review_pr(
    owner: str, 
    repo: str, 
    pr: int, 
    token: str, 
    client: httpx.AsyncClient, 
    event: str, 
    message: str, 
    comments: Optional[List[Dict]] = None
) -> None:
    """Submits a comprehensive formal GitHub Pull Request Review.

    Can optionally distribute grouped line-level inline comments across distinct 
    files along with a top-level validation verdict state.

    Args:
        owner (str): Owner or organization name of the repository.
        repo (str): Name of the repository.
        pr (int): Target Pull Request ID number.
        token (str): Repository installation access token.
        client (httpx.AsyncClient): HTTPX async client to process network requests.
        event (str): Review decision action token string (e.g., "APPROVE", "REQUEST_CHANGES").
        message (str): Top-level markdown comment detailing review justification.
        comments (Optional[List[Dict]]): Array of inline file comment entities. Defaults to None.
    """
    payload = {"event": event, "body": message}
    if comments:
        payload["comments"] = comments

    res = await client.post(
        f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr}/reviews",
        headers={"Authorization": f"Bearer {token}"},
        json=payload
    )
    if res.status_code not in [200, 201]:
        logger.error(f"Failed to submit PR review: {res.text}")


def should_auto_approve(files: List[Dict]) -> bool:
    """Evaluates size metrics of altered file records to determine safety for automated approvals.

    Args:
        files (List[Dict]): Parsed structural array listing file parameters inside a PR.

    Returns:
        bool: True if file count threshold limits are respected, otherwise False.
    """
    return len(files) <= 20


# -----------------------------
# 🧠 Dynamic Analysis Pipeline
# -----------------------------
async def process_pr_pipeline(owner: str, repo: str, pr_number: int, token: str, client: httpx.AsyncClient) -> Dict:
    """Executes the complete operational pipeline to fetch, parse, and review a target PR.

    Downloads full PR metadata tracking base/head SHAs, downloads lists of updated files,
    evaluates lines of code within specific matching targets (`fastapi_simple/api.py`, 
    `tests/test_health.py`) for custom rule-based recommendations, and submits a 
    consolidated review verdict.

    Args:
        owner (str): Owner or organization name of the repository.
        repo (str): Name of the repository.
        pr_number (int): Target Pull Request ID number.
        token (str): Repository installation access token.
        client (httpx.AsyncClient): HTTPX async client to process network requests.

    Returns:
        Dict: Summary tracking results outlining execution milestones and comments posted.
    """
    # 1. Fetch targeted PR metadata directly
    pr_data = await fetch_single_pull_request(owner, repo, pr_number, token, client)
    
    base_sha = pr_data["base"]["sha"]
    head_sha = pr_data["head"]["sha"]

    logger.info(f"Processing single request execution for PR #{pr_number}...")
    
    files = await fetch_pr_files(owner, repo, pr_number, token, client)
    
    # Simple list comprehension to classify files instead of full gather overhead
    structured_files = []
    batched_comments = []
    
    for f in files:
        filename = f["filename"]
        status = f.get("status", "modified")
        structured_files.append({"file": filename, "status": status})
        
        # Pull raw content directly for target evaluations
        if filename.endswith(".py"):
            after_content = await fetch_file_content(owner, repo, filename, head_sha, token, client)
            if after_content:
                lines = after_content.splitlines()
                for line_idx, line_text in enumerate(lines, start=1):
                    
                    if "fastapi_simple/api.py" in filename:
                        if "@router." in lines[line_idx - 2 if line_idx > 1 else 0] and "def " in line_text and "async def" not in line_text:
                            batched_comments.append({
                                "path": filename, "line": line_idx, "side": "RIGHT",
                                "body": "💡 **PR Bot Optimization:** Consider implementing this endpoint using `async def`..."
                            })
                        if "def greet" in line_text and "->" not in line_text:
                            batched_comments.append({
                                "path": filename, "line": line_idx, "side": "RIGHT",
                                "body": "📝 **PR Bot Style Guide:** It's highly recommended to provide an explicit return type signature hint here."
                            })

                    if "tests/test_health.py" in filename:
                        if "def test_greet_default" in line_text:
                            batched_comments.append({
                                "path": filename, "line": line_idx, "side": "RIGHT",
                                "body": "🧪 **PR Bot Quality Check:** Outstanding test coverage definitions! Add an inline docstring."
                            })

    comment = PRComment(
        title="✅ PR Processed Successfully (On-Demand Mode)",
        summary=f"All files analyzed. Found {len(batched_comments)} inline file review notifications.",
        pr_number=pr_number,
        repository=f"{owner}/{repo}",
        total_files=len(structured_files),
        file_stats=FileStats(
            added=[f["file"] for f in structured_files if f["status"] == "added"],
            modified=[f["file"] for f in structured_files if f["status"] == "modified"],
            removed=[f["file"] for f in structured_files if f["status"] == "removed"],
        ),
        notes="Auto-approved because changes are small." if should_auto_approve(structured_files) else None
    )

    is_small = should_auto_approve(structured_files)
    review_event = "APPROVE" if is_small else "REQUEST_CHANGES"
    review_msg = "✅ Auto-approved changes via Manual API call request." if is_small else "⚠️ Too large PR"

    # Post comments and wrap review submission
    await comment_pr(owner, repo, pr_number, comment, token, client)
    await review_pr(owner, repo, pr_number, token, client, review_event, review_msg, batched_comments)
    
    return {
        "status": "success",
        "repository": f"{owner}/{repo}",
        "pr_number": pr_number,
        "files_counted": len(structured_files),
        "comments_posted": len(batched_comments)
    }


# -----------------------------
# 🌐 Lifespan Initialization
# -----------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manages the operational lifecycle setup and breakdown for the FastAPI application.

    Configures and provisions a shared asynchronous HTTPX connection pool on application startup, 
    mounting it directly to `app.state.client`, and gracefully cleans up resources upon shutdown.
    """
    timeout = httpx.Timeout(timeout=10.0, connect=10.0, read=45.0, write=10.0, pool=10.0)
    limits = httpx.Limits(max_connections=50, max_keepalive_connections=20)

    async with httpx.AsyncClient(timeout=timeout, limits=limits, headers={"Accept": "application/vnd.github+json"}) as client:
        app.state.client = client
        logger.info("HTTP Client Session safely locked in.")
        yield
    logger.info("HTTP Client Session cleanly broken down.")


app = FastAPI(title="GitHub PR Bot Router Only", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# -----------------------------
# 🔥 Review Target Routing Endpoint
# -----------------------------
@app.post("/review-pr")
async def trigger_pr_review(
    owner: str = Query(..., description="GitHub repository owner"),
    repo: str = Query(..., description="GitHub repository name"),
    pr_number: int = Query(..., description="Target Pull Request ID number")
):
    """Triggers an instantaneous, one-shot metadata pull and review analysis for a specific PR.

    Validates installation access token permissions for the target repository context, 
    routes requirements to the evaluation analyzer pipeline, and returns execution metrics.
    """
    client = app.state.client
    
    token = await get_installation_token_by_repo(owner, repo, client)
    if not token:
        raise HTTPException(
            status_code=401, 
            detail=f"Could not authorize GitHub App permissions installation mapping for target metadata {owner}/{repo}"
        )
        
    try:
        result = await process_pr_pipeline(owner, repo, pr_number, token, client)
        return result
    except Exception as e:
        logger.error(f"Execution pipeline breakdown on PR #{pr_number}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
