name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip poetry
      - run: poetry install --no-interaction --no-ansi
      - run: poetry build
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'  # 👉 only upload dist on main pushes, not PRs
        with:
          name: dist
          path: dist
