name: CI (Lint + Test + Build)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip poetry
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run ruff check .
      - run: poetry run ruff format --check .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip poetry
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run pytest -q

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip poetry
      - run: poetry install --no-interaction --no-ansi
      - run: poetry build
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push' # only save artifacts on main pushes
        with:
          name: dist
          path: dist
