name: Lint & Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip poetry
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run ruff check .
      - run: poetry run ruff format --check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip poetry
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run pytest -q
