name: Tag & Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  contents: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | cut -d '"' -f2)
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        run: |
          if git rev-parse ${{ steps.version.outputs.version }} >/dev/null 2>&1; then
            echo "❌ Tag ${{ steps.version.outputs.version }} already exists"
            exit 1
          fi

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
